import { NavLink, Route, Routes, Navigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';

import { SyntheticDataBanner } from './components/aurora';
import { api } from './lib/api';
import { ThemeToggle } from './components/ThemeToggle';
import { AuroraRoute } from './screens/AuroraRoute';
import { Templates } from './screens/Templates';
import { PackRun } from './screens/PackRun';
import { Review } from './screens/Review';
import { SignOff } from './screens/SignOff';
import { Archive } from './screens/Archive';
import { MonthDiff } from './screens/MonthDiff';

const NAV = [
  { to: '/templates', label: 'Templates', hint: 'Define the pack once' },
  { to: '/run', label: 'Pack run', hint: 'Assemble a period' },
  { to: '/review', label: 'Review', hint: 'Edit and approve' },
  { to: '/signoff', label: 'Sign-off', hint: 'Resolve gaps and sign' },
  { to: '/archive', label: 'Archive', hint: 'Issued packs' },
  { to: '/diff', label: 'Month diff', hint: 'Same structure, new numbers' },
];

export default function App() {
  const health = useQuery({ queryKey: ['health'], queryFn: api.health, retry: 1 });

  return (
    <div className="rs-shell">
      <a className="rs-skip" href="#main">
        Skip to content
      </a>

      <header className="rs-header">
        <div className="rs-brand">
          <span className="rs-brand-mark" aria-hidden />
          <div>
            <h1>ReportSmith</h1>
            <p>Define the pack once. Review forever after.</p>
          </div>
        </div>

        <nav className="rs-nav" aria-label="Main">
          {NAV.map((item) => (
            <NavLink
              key={item.to}
              to={item.to}
              title={item.hint}
              className={({ isActive }) => `rs-nav-item${isActive ? ' is-active' : ''}`}
            >
              {item.label}
            </NavLink>
          ))}
        </nav>

        <div className="rs-header-right">
          {/* The LLM mode is always visible. A screenshot of this product must never be
              mistakable for one where a real model drafted the prose. */}
          {health.data && (
            <span
              className={`rs-badge ${health.data.llm === 'live' ? 'rs-badge-amber' : 'rs-badge-slate'}`}
              title={
                health.data.llm === 'live'
                  ? `Narratives drafted by ${health.data.model}`
                  : 'Narratives drafted by the deterministic mock — no model, no cost'
              }
            >
              <span aria-hidden>{health.data.llm === 'live' ? '◆' : '◌'}</span>
              {health.data.llm === 'live' ? `live · ${health.data.model}` : 'mock LLM'}
            </span>
          )}
          <ThemeToggle />
        </div>
      </header>

      <SyntheticDataBanner />

      <main id="main" className="rs-main">
        <Routes>
          <Route path="/" element={<Navigate to="/run" replace />} />
          <Route path="/templates" element={<Templates />} />
          <Route path="/run" element={<PackRun />} />
          <Route path="/review" element={<Review />} />
          <Route path="/review/:packId" element={<Review />} />
          <Route path="/signoff" element={<SignOff />} />
          <Route path="/signoff/:packId" element={<SignOff />} />
          <Route path="/archive" element={<Archive />} />
          <Route path="/diff" element={<MonthDiff />} />
          <Route path="/aurora" element={<AuroraRoute />} />
          <Route
            path="*"
            element={
              <div className="rs-empty">
                <h3>No such screen</h3>
                <p>Pick one from the navigation above.</p>
              </div>
            }
          />
        </Routes>
      </main>

      <footer className="rs-footer">
        <span>
          All data synthetic · generated by <code>ledgerfab</code>
        </span>
        <NavLink to="/aurora">aurora components</NavLink>
      </footer>
    </div>
  );
}
