"""The extended chart of accounts, and the canonical statement-line vocabulary.

Two things live here, and the second is the more important one.

**The chart.** The vendored engine's 14 accounts describe a purchase cycle: cash, AR,
prepayments, AP, accruals, VAT, share capital, revenue and five expense accounts. That
is enough to reconcile a bank statement and nowhere near enough to draw a balance
sheet — there is no inventory, no fixed asset, no debt, no tax and no retained
earnings. ``STATEMENT_ACCOUNTS`` is that chart plus the accounts a set of statements
needs, with every base code preserved so a world generated by ``ledgerfab.generate``
and a statement set generated here speak the same language.

**The vocabulary.** ``STATEMENT_LINES`` is the one canonical list of line codes. The
emitter writes it, the CSV/XLSX template is generated from it, the parser validates
against it, and every formula addresses lines by it. Declaring it once — here, on the
engine side of the one-way import rule — is what stops the generate path and the
upload path from drifting apart (PLAN.md **D-004**).

Each line carries its own **sign convention** as data rather than as folklore, because
sign is exactly the thing that silently breaks a ratio:

* ``magnitude`` — always ≥ 0 as presented. Revenue, cost of sales, accumulated
  depreciation, accounts payable. A reader sees ``Cost of sales 1,240,000``, not
  ``-1,240,000``.
* ``signed`` — may be negative and means it. Subtotals (``net_income``), equity
  (``retained_earnings`` — negative equity is a case this project must handle, not
  avoid), and **every** cash-flow line, where inflow-positive makes ``cf_operating``
  a plain sum of its children.

Subtotals declare their components as ``(line_code, coefficient)`` pairs, so
``gross_profit = revenue − cogs`` and ``ppe_net = ppe_gross − accumulated_depreciation``
are data too. `derive.py` computes every subtotal from that declaration; nothing
hand-codes an addition.
"""

from __future__ import annotations

from dataclasses import dataclass

# --------------------------------------------------------------------- accounts --

#: Natural balance side per account type. Assets and expenses are debit-positive;
#: liabilities, equity and income are credit-positive. ``contra_asset`` (accumulated
#: depreciation) is an asset-section account that is credit-positive, which is why it
#: needs its own type rather than a special case somewhere downstream.
NATURAL_DEBIT: dict[str, bool] = {
    "asset": True,
    "contra_asset": False,
    "liability": False,
    "equity": False,
    "income": False,
    "expense": True,
}

#: ``True`` for accounts whose balance is a *flow* closed to retained earnings at each
#: period end, ``False`` for the *stock* accounts that carry forward.
IS_PROFIT_AND_LOSS: dict[str, bool] = {
    "asset": False,
    "contra_asset": False,
    "liability": False,
    "equity": False,
    "income": True,
    "expense": True,
}


@dataclass(frozen=True, slots=True)
class StatementAccount:
    code: str
    name: str
    type: str
    #: ``True`` for the two bank accounts. The cash-flow statement is built by asking
    #: which side of a journal entry was cash, so this flag is load-bearing.
    is_cash: bool = False
    #: Which cash-flow section a movement against this account belongs to, when it
    #: sits opposite cash in a journal entry. `derive.py` reads this instead of
    #: requiring every posting to be hand-tagged — a tag is a thing to get wrong.
    cf_section: str = "operating"
    #: `False` for accounts inherited from the base chart that this emitter models.
    added_by_extension: bool = True


# Base-chart codes are preserved exactly as `ledgerfab.generators.companies` defines
# them, so the two engines never disagree about what "1100" means.
STATEMENT_ACCOUNTS: tuple[StatementAccount, ...] = (
    # -- assets ---------------------------------------------------------------
    StatementAccount(
        "1000", "Cash at bank — current", "asset", is_cash=True, added_by_extension=False
    ),
    StatementAccount(
        "1010", "Cash at bank — deposit", "asset", is_cash=True, added_by_extension=False
    ),
    StatementAccount("1100", "Accounts receivable", "asset", added_by_extension=False),
    StatementAccount("1200", "Prepayments", "asset", added_by_extension=False),
    StatementAccount("1300", "Inventory", "asset"),
    StatementAccount("1500", "Property, plant & equipment — cost", "asset", cf_section="investing"),
    StatementAccount("1590", "Accumulated depreciation", "contra_asset", cf_section="investing"),
    # -- liabilities ----------------------------------------------------------
    StatementAccount("2000", "Accounts payable", "liability", added_by_extension=False),
    StatementAccount("2100", "Accruals", "liability", added_by_extension=False),
    StatementAccount("2200", "VAT control", "liability", added_by_extension=False),
    StatementAccount("2300", "Corporation tax payable", "liability"),
    StatementAccount("2400", "Short-term debt", "liability", cf_section="financing"),
    StatementAccount("2500", "Long-term debt", "liability", cf_section="financing"),
    # -- equity ---------------------------------------------------------------
    StatementAccount(
        "3000", "Share capital", "equity", cf_section="financing", added_by_extension=False
    ),
    StatementAccount("3100", "Retained earnings", "equity", cf_section="financing"),
    StatementAccount("3200", "Dividends declared", "equity", cf_section="financing"),
    # -- income ---------------------------------------------------------------
    StatementAccount("4000", "Revenue", "income", added_by_extension=False),
    # -- expenses -------------------------------------------------------------
    StatementAccount("5000", "Cost of sales", "expense", added_by_extension=False),
    StatementAccount("6000", "Professional fees", "expense", added_by_extension=False),
    StatementAccount("6100", "Software subscriptions", "expense", added_by_extension=False),
    StatementAccount("6200", "Rent", "expense", added_by_extension=False),
    StatementAccount("6300", "Utilities", "expense", added_by_extension=False),
    StatementAccount("6400", "Payroll", "expense"),
    StatementAccount("6500", "Selling & marketing", "expense"),
    StatementAccount("6900", "Depreciation", "expense"),
    StatementAccount("7000", "Interest expense", "expense", cf_section="operating"),
    StatementAccount("8000", "Corporation tax", "expense"),
)

ACCOUNTS_BY_CODE: dict[str, StatementAccount] = {a.code: a for a in STATEMENT_ACCOUNTS}
CASH_CODES: tuple[str, ...] = tuple(a.code for a in STATEMENT_ACCOUNTS if a.is_cash)

# Named codes the posting engine reaches for. Spelled out rather than inlined so a
# chart change is a one-line edit here and not a search across the emitter.
CASH_CURRENT = "1000"
CASH_DEPOSIT = "1010"
RECEIVABLES = "1100"
PREPAYMENTS = "1200"
INVENTORY = "1300"
PPE_COST = "1500"
ACCUM_DEPRECIATION = "1590"
PAYABLES = "2000"
ACCRUALS = "2100"
TAX_PAYABLE = "2300"
DEBT_SHORT = "2400"
DEBT_LONG = "2500"
SHARE_CAPITAL = "3000"
RETAINED_EARNINGS = "3100"
DIVIDENDS = "3200"
REVENUE = "4000"
COST_OF_SALES = "5000"
PROFESSIONAL_FEES = "6000"
SOFTWARE = "6100"
RENT = "6200"
UTILITIES = "6300"
PAYROLL = "6400"
SELLING = "6500"
DEPRECIATION = "6900"
INTEREST = "7000"
TAX_EXPENSE = "8000"

#: The admin expense accounts, aggregated into one presented line.
ADMIN_CODES: tuple[str, ...] = (PROFESSIONAL_FEES, SOFTWARE, RENT, UTILITIES)


def is_debit_positive(code: str) -> bool:
    return NATURAL_DEBIT[ACCOUNTS_BY_CODE[code].type]


def is_pnl_account(code: str) -> bool:
    return IS_PROFIT_AND_LOSS[ACCOUNTS_BY_CODE[code].type]


# ---------------------------------------------------------------- statement lines --

PNL = "pnl"
BS = "bs"
CF = "cf"

MAGNITUDE = "magnitude"
SIGNED = "signed"


@dataclass(frozen=True, slots=True)
class StatementLineDef:
    """One line of one statement, and everything the rest of the system needs to know
    about it: where it comes from, how it is signed, and whether it is a subtotal."""

    code: str
    label: str
    statement: str
    section: str
    sign: str
    #: Source accounts, for lines drawn straight from the trial balance. Empty for
    #: subtotals and for cash-flow lines, which are derived rather than posted.
    accounts: tuple[str, ...] = ()
    #: ``(line_code, coefficient)`` pairs. Present iff this line is a subtotal.
    subtotal_of: tuple[tuple[str, int], ...] | None = None
    #: ``False`` for lines a hand-prepared upload may legitimately omit.
    required: bool = True

    @property
    def is_subtotal(self) -> bool:
        return self.subtotal_of is not None


def _line(
    code: str,
    label: str,
    statement: str,
    section: str,
    sign: str,
    *,
    accounts: tuple[str, ...] = (),
    subtotal_of: tuple[tuple[str, int], ...] | None = None,
    required: bool = True,
) -> StatementLineDef:
    return StatementLineDef(code, label, statement, section, sign, accounts, subtotal_of, required)


STATEMENT_LINES: tuple[StatementLineDef, ...] = (
    # ============================================================ profit & loss ==
    _line("revenue", "Revenue", PNL, "trading", MAGNITUDE, accounts=(REVENUE,)),
    _line("cogs", "Cost of sales", PNL, "trading", MAGNITUDE, accounts=(COST_OF_SALES,)),
    _line(
        "gross_profit",
        "Gross profit",
        PNL,
        "trading",
        SIGNED,
        subtotal_of=(("revenue", 1), ("cogs", -1)),
    ),
    _line("opex_payroll", "Payroll", PNL, "operating", MAGNITUDE, accounts=(PAYROLL,)),
    _line("opex_selling", "Selling & marketing", PNL, "operating", MAGNITUDE, accounts=(SELLING,)),
    _line(
        "opex_admin", "Administrative expenses", PNL, "operating", MAGNITUDE, accounts=ADMIN_CODES
    ),
    _line("depreciation", "Depreciation", PNL, "operating", MAGNITUDE, accounts=(DEPRECIATION,)),
    _line(
        "operating_expenses",
        "Total operating expenses",
        PNL,
        "operating",
        SIGNED,
        subtotal_of=(
            ("opex_payroll", 1),
            ("opex_selling", 1),
            ("opex_admin", 1),
            ("depreciation", 1),
        ),
    ),
    _line(
        "operating_profit",
        "Operating profit",
        PNL,
        "operating",
        SIGNED,
        subtotal_of=(("gross_profit", 1), ("operating_expenses", -1)),
    ),
    _line(
        "interest_expense", "Interest expense", PNL, "financing", MAGNITUDE, accounts=(INTEREST,)
    ),
    _line(
        "pretax_profit",
        "Profit before tax",
        PNL,
        "financing",
        SIGNED,
        subtotal_of=(("operating_profit", 1), ("interest_expense", -1)),
    ),
    _line("tax_expense", "Tax", PNL, "financing", MAGNITUDE, accounts=(TAX_EXPENSE,)),
    _line(
        "net_income",
        "Net income",
        PNL,
        "financing",
        SIGNED,
        subtotal_of=(("pretax_profit", 1), ("tax_expense", -1)),
    ),
    # =========================================================== balance sheet ==
    _line(
        "cash",
        "Cash and cash equivalents",
        BS,
        "current_assets",
        MAGNITUDE,
        accounts=(CASH_CURRENT, CASH_DEPOSIT),
    ),
    _line(
        "accounts_receivable",
        "Accounts receivable",
        BS,
        "current_assets",
        MAGNITUDE,
        accounts=(RECEIVABLES,),
    ),
    _line("inventory", "Inventory", BS, "current_assets", MAGNITUDE, accounts=(INVENTORY,)),
    _line(
        "prepayments",
        "Prepayments",
        BS,
        "current_assets",
        MAGNITUDE,
        accounts=(PREPAYMENTS,),
        required=False,
    ),
    _line(
        "total_current_assets",
        "Total current assets",
        BS,
        "current_assets",
        SIGNED,
        subtotal_of=(("cash", 1), ("accounts_receivable", 1), ("inventory", 1), ("prepayments", 1)),
    ),
    _line(
        "ppe_gross",
        "Property, plant & equipment — cost",
        BS,
        "non_current_assets",
        MAGNITUDE,
        accounts=(PPE_COST,),
    ),
    _line(
        "accumulated_depreciation",
        "Less: accumulated depreciation",
        BS,
        "non_current_assets",
        MAGNITUDE,
        accounts=(ACCUM_DEPRECIATION,),
    ),
    _line(
        "ppe_net",
        "Property, plant & equipment — net",
        BS,
        "non_current_assets",
        SIGNED,
        subtotal_of=(("ppe_gross", 1), ("accumulated_depreciation", -1)),
    ),
    _line(
        "total_non_current_assets",
        "Total non-current assets",
        BS,
        "non_current_assets",
        SIGNED,
        subtotal_of=(("ppe_net", 1),),
    ),
    _line(
        "total_assets",
        "Total assets",
        BS,
        "assets",
        SIGNED,
        subtotal_of=(("total_current_assets", 1), ("total_non_current_assets", 1)),
    ),
    _line(
        "accounts_payable",
        "Accounts payable",
        BS,
        "current_liabilities",
        MAGNITUDE,
        accounts=(PAYABLES,),
    ),
    _line(
        "accruals",
        "Accruals",
        BS,
        "current_liabilities",
        MAGNITUDE,
        accounts=(ACCRUALS,),
        required=False,
    ),
    _line(
        "vat_payable",
        "VAT control",
        BS,
        "current_liabilities",
        MAGNITUDE,
        accounts=("2200",),
        required=False,
    ),
    _line(
        "tax_payable",
        "Tax payable",
        BS,
        "current_liabilities",
        MAGNITUDE,
        accounts=(TAX_PAYABLE,),
        required=False,
    ),
    _line(
        "short_term_debt",
        "Short-term debt",
        BS,
        "current_liabilities",
        MAGNITUDE,
        accounts=(DEBT_SHORT,),
        required=False,
    ),
    _line(
        "total_current_liabilities",
        "Total current liabilities",
        BS,
        "current_liabilities",
        SIGNED,
        subtotal_of=(
            ("accounts_payable", 1),
            ("accruals", 1),
            ("vat_payable", 1),
            ("tax_payable", 1),
            ("short_term_debt", 1),
        ),
    ),
    _line(
        "long_term_debt",
        "Long-term debt",
        BS,
        "non_current_liabilities",
        MAGNITUDE,
        accounts=(DEBT_LONG,),
        required=False,
    ),
    _line(
        "total_non_current_liabilities",
        "Total non-current liabilities",
        BS,
        "non_current_liabilities",
        SIGNED,
        subtotal_of=(("long_term_debt", 1),),
    ),
    _line(
        "total_liabilities",
        "Total liabilities",
        BS,
        "liabilities",
        SIGNED,
        subtotal_of=(("total_current_liabilities", 1), ("total_non_current_liabilities", 1)),
    ),
    _line("share_capital", "Share capital", BS, "equity", MAGNITUDE, accounts=(SHARE_CAPITAL,)),
    # SIGNED, and this is the point: negative retained earnings (and therefore
    # negative equity) is a case the computation engine is required to handle.
    _line(
        "retained_earnings",
        "Retained earnings",
        BS,
        "equity",
        SIGNED,
        accounts=(RETAINED_EARNINGS, DIVIDENDS),
    ),
    _line(
        "total_equity",
        "Total equity",
        BS,
        "equity",
        SIGNED,
        subtotal_of=(("share_capital", 1), ("retained_earnings", 1)),
    ),
    _line(
        "total_liabilities_and_equity",
        "Total liabilities and equity",
        BS,
        "equity",
        SIGNED,
        subtotal_of=(("total_liabilities", 1), ("total_equity", 1)),
    ),
    # ========================================================= cash flow (indirect) ==
    # Every line SIGNED, inflow-positive, so each subtotal is a plain sum.
    _line("cf_net_income", "Net income", CF, "operating", SIGNED),
    _line("cf_depreciation", "Add back: depreciation", CF, "operating", SIGNED),
    _line("cf_change_receivables", "Change in receivables", CF, "operating", SIGNED),
    _line("cf_change_inventory", "Change in inventory", CF, "operating", SIGNED),
    _line("cf_change_prepayments", "Change in prepayments", CF, "operating", SIGNED),
    _line("cf_change_payables", "Change in payables", CF, "operating", SIGNED),
    _line("cf_change_accruals", "Change in accruals", CF, "operating", SIGNED),
    _line("cf_change_tax_payable", "Change in tax payable", CF, "operating", SIGNED),
    _line(
        "cf_operating",
        "Net cash from operating activities",
        CF,
        "operating",
        SIGNED,
        subtotal_of=(
            ("cf_net_income", 1),
            ("cf_depreciation", 1),
            ("cf_change_receivables", 1),
            ("cf_change_inventory", 1),
            ("cf_change_prepayments", 1),
            ("cf_change_payables", 1),
            ("cf_change_accruals", 1),
            ("cf_change_tax_payable", 1),
        ),
    ),
    _line("cf_capex", "Purchase of fixed assets", CF, "investing", SIGNED),
    _line(
        "cf_investing",
        "Net cash from investing activities",
        CF,
        "investing",
        SIGNED,
        subtotal_of=(("cf_capex", 1),),
    ),
    _line("cf_debt_drawn", "Debt drawn", CF, "financing", SIGNED),
    _line("cf_debt_repaid", "Debt repaid", CF, "financing", SIGNED),
    _line("cf_equity_issued", "Equity issued", CF, "financing", SIGNED),
    _line("cf_dividends_paid", "Dividends paid", CF, "financing", SIGNED),
    _line(
        "cf_financing",
        "Net cash from financing activities",
        CF,
        "financing",
        SIGNED,
        subtotal_of=(
            ("cf_debt_drawn", 1),
            ("cf_debt_repaid", 1),
            ("cf_equity_issued", 1),
            ("cf_dividends_paid", 1),
        ),
    ),
    _line(
        "cf_net_change_in_cash",
        "Net change in cash",
        CF,
        "summary",
        SIGNED,
        subtotal_of=(("cf_operating", 1), ("cf_investing", 1), ("cf_financing", 1)),
    ),
    _line("cf_cash_open", "Cash at start of period", CF, "summary", SIGNED),
    _line(
        "cf_cash_close",
        "Cash at end of period",
        CF,
        "summary",
        SIGNED,
        subtotal_of=(("cf_cash_open", 1), ("cf_net_change_in_cash", 1)),
    ),
)

LINES_BY_CODE: dict[str, StatementLineDef] = {ln.code: ln for ln in STATEMENT_LINES}
LINE_ORDER: dict[str, int] = {ln.code: i for i, ln in enumerate(STATEMENT_LINES)}


def lines_for(statement: str) -> tuple[StatementLineDef, ...]:
    return tuple(ln for ln in STATEMENT_LINES if ln.statement == statement)


def cash_flow_section(code: str) -> str:
    """Which cash-flow section a movement against this account belongs to."""
    return ACCOUNTS_BY_CODE[code].cf_section
