/**
 * Card, MetricTile, EmptyState, SyntheticDataBanner — spec 00 A2.
 *
 * The surfaces a screen is built out of. Grouped because they share the frosted-glass
 * treatment and nothing else in the system needs them individually.
 */

import type { ReactNode } from 'react';

export interface CardProps {
  children: ReactNode;
  title?: ReactNode;
  subtitle?: ReactNode;
  /** Rendered at the right of the header — a badge, a filter, an action. */
  actions?: ReactNode;
  variant?: 'default' | 'raised' | 'flat';
  /** Drop the body padding, for a card that contains a full-bleed table. */
  tight?: boolean;
  className?: string;
}

/** The frosted-glass surface. Spec 00 A2's `Card`. */
export function Card({
  children,
  title,
  subtitle,
  actions,
  variant = 'default',
  tight = false,
  className = '',
}: CardProps) {
  const classes = ['au-card'];
  if (variant !== 'default') classes.push(`au-card--${variant}`);
  if (className) classes.push(className);

  return (
    <section className={classes.join(' ')} data-testid="card">
      {title || actions ? (
        <header className="au-card__head">
          <div>
            <div className="au-card__title">{title}</div>
            {subtitle ? <div className="au-card__subtitle">{subtitle}</div> : null}
          </div>
          {actions ? <div>{actions}</div> : null}
        </header>
      ) : null}
      <div className={tight ? 'au-card__body au-card__body--tight' : 'au-card__body'}>
        {children}
      </div>
    </section>
  );
}

export interface MetricTileProps {
  label: string;
  value: ReactNode;
  hint?: ReactNode;
  tone?: 'neutral' | 'accent' | 'warn' | 'bad';
  className?: string;
}

/**
 * One number, large. Spec 00 A2's `MetricTile`.
 *
 * `hint` exists because a bare number in a governance console is a liability: "0.88" means
 * nothing without "floor 0.85", and a reviewer should not have to know the floor by heart to
 * read the screen.
 */
export function MetricTile({
  label,
  value,
  hint,
  tone = 'neutral',
  className = '',
}: MetricTileProps) {
  const classes = ['au-tile'];
  if (tone !== 'neutral') classes.push(`au-tile--${tone}`);
  if (className) classes.push(className);

  return (
    <div className={classes.join(' ')} data-testid="metric-tile">
      <div className="au-tile__label">{label}</div>
      <div className="au-tile__value">{value}</div>
      {hint ? <div className="au-tile__hint">{hint}</div> : null}
    </div>
  );
}

export interface EmptyStateProps {
  title: string;
  /**
   * What to do about it. Required rather than optional, on purpose: every empty state in this
   * console is a state a reviewer might read as "the agent did nothing", and the hint is what
   * distinguishes "nothing to review — all 38 auto-posted" from "no runs yet".
   */
  hint: string;
  glyph?: string;
  action?: ReactNode;
}

export function EmptyState({ title, hint, glyph = '◌', action }: EmptyStateProps) {
  return (
    <div className="au-empty" data-testid="empty-state">
      <div className="au-empty__glyph" aria-hidden="true">
        {glyph}
      </div>
      <div className="au-empty__title">{title}</div>
      <p className="au-empty__hint">{hint}</p>
      {action ? <div className="au-empty__action">{action}</div> : null}
    </div>
  );
}

export interface SyntheticDataBannerProps {
  profile?: string | null;
  seed?: number | null;
}

/**
 * Spec 00 A1 and A2 both require this, and spec 06 §11 is the reason: *"Synthetic data only."*
 *
 * Always visible, never dismissible. This console shows bank transactions, payee names and
 * amounts; a screenshot of it will end up in a post or a slide, and the banner is what stops
 * anyone wondering whose books they are looking at. Making it dismissible would guarantee the
 * screenshot without it.
 *
 * The profile and seed are shown when known, because "realistic / seed 42" is what makes the
 * data reproducible rather than merely fake.
 */
export function SyntheticDataBanner({ profile, seed }: SyntheticDataBannerProps) {
  return (
    <div className="au-synthetic" role="note" data-testid="synthetic-banner">
      <span aria-hidden="true">⚠</span>
      <span>All data is synthetic.</span>
      <span className="au-synthetic__detail">
        Generated by ledgerfab
        {profile ? ` · ${profile}` : ''}
        {seed !== null && seed !== undefined ? ` / seed ${seed}` : ''} — no real company,
        counterparty or transaction appears anywhere.
      </span>
    </div>
  );
}
