"""Pack → markdown. The archive's primary artefact, and what the PDF is built from.

Gaps are rendered **into** the document, not omitted from it (spec 13 F2). An issued pack
that silently lacks a section is the failure this product exists to prevent, so a gapped
section appears with its reason and, if one was recorded, the waiver that let the pack go
out without it. A reader of the archive can see exactly what was missing and who accepted
that.
"""

from __future__ import annotations

from typing import Any


def _table(content: dict[str, Any]) -> list[str]:
    columns = content.get("columns", [])
    if not columns:
        return ["_No columns._"]

    header = "| " + " | ".join(c["label"] or " " for c in columns) + " |"
    align = (
        "| "
        + " | ".join(
            {"right": "---:", "center": ":---:"}.get(c.get("align", "left"), ":---")
            for c in columns
        )
        + " |"
    )
    lines = [header, align]

    for row in content.get("rows", []):
        lines.append(
            "| "
            + " | ".join(str(row.get(c["field"], {}).get("display", "")) for c in columns)
            + " |"
        )

    total = content.get("total")
    if total:
        lines.append(
            "| "
            + " | ".join(f"**{total.get(c['field'], {}).get('display', '')}**" for c in columns)
            + " |"
        )

    if content.get("truncated_from"):
        lines += [
            "",
            f"_Showing {content.get('row_count')} of {content['truncated_from']} rows._",
        ]
    return lines


def _kpi_grid(content: dict[str, Any]) -> list[str]:
    lines = ["| Measure | This month | Prior month | Change |", "| :--- | ---: | ---: | ---: |"]
    for kpi in content.get("kpis", []):
        if kpi.get("missing"):
            lines.append(f"| {kpi['label']} | _unavailable_ | | |")
            continue
        lines.append(
            f"| {kpi['label']} | {kpi['display']} | {kpi.get('prior_display', '')} "
            f"| {kpi.get('delta_display', '')} |"
        )
    return lines


def _flags(content: dict[str, Any]) -> list[str]:
    items = content.get("items", [])
    if not items:
        return ["_No items were flagged this period._"]
    lines: list[str] = []
    for item in items:
        head = f"**{item['label']}** ({item['severity']})"
        if item.get("amount_display"):
            head += f" — {item['amount_display']}"
        lines.append(f"- {head}")
        if item.get("message"):
            lines.append(f"  {item['message']}")
        if item.get("evidence"):
            lines.append(f"  _Evidence: {item['evidence']}_")
    return lines


def _narrative(content: dict[str, Any]) -> list[str]:
    text = (content.get("text") or "").strip()
    if not text:
        return ["_Not drafted._"]
    lines = [text]
    if content.get("dropped_sentences"):
        # Recorded in the document, not just in the database. A sentence removed because
        # its figure could not be verified is a fact about how this pack was produced,
        # and burying it would defeat the point of having caught it.
        lines += [
            "",
            f"> _{len(content['dropped_sentences'])} sentence(s) were removed during drafting "
            f"because a figure could not be verified against the bound data._",
        ]
    return lines


def render_markdown(
    pack: dict[str, Any],
    sections: list[dict[str, Any]],
    *,
    waivers: list[dict[str, Any]] | None = None,
    signoff: dict[str, Any] | None = None,
) -> str:
    cover = pack.get("cover", {})
    waiver_by_section = {w["section_key"]: w for w in (waivers or [])}

    lines: list[str] = [
        f"# {cover.get('title', 'Report pack')}",
        "",
        f"**Period:** {pack['period']}  ",
        f"**Template:** `{pack['template_ref']}`  ",
        f"**Status:** {pack['status']}",
        "",
        "> ⚠️ **All data is synthetic.** Generated by `ledgerfab` for demonstration.",
        "",
        "## Contents",
        "",
    ]
    for index, section in enumerate(sections, 1):
        mark = " — **GAP**" if section.get("gaps_json") else ""
        lines.append(f"{index}. {section['title']}{mark}")
    lines.append("")

    for section in sections:
        lines += ["---", "", f"## {section['title']}", ""]
        gaps = section.get("gaps_json") or []
        if gaps:
            for gap in gaps:
                lines += [
                    f"> **Not available.** `{gap['reason']}` — {gap['detail']}",
                    "",
                ]
            waiver = waiver_by_section.get(section["section_key"])
            if waiver:
                lines += [
                    f"> _Waived by {waiver['signer']}: {waiver['reason']}_",
                    "",
                ]
            continue

        content = section.get("content_json") or {}
        kind = section["type"]
        if kind == "table":
            lines += _table(content)
        elif kind == "kpi_grid":
            lines += _kpi_grid(content)
        elif kind == "flags":
            lines += _flags(content)
        elif kind == "narrative":
            lines += _narrative(content)
        lines.append("")

    if signoff:
        lines += [
            "---",
            "",
            "## Sign-off",
            "",
            f"Signed by **{signoff['signer']}** at {signoff['at']}.",
            "",
        ]
        if waivers:
            lines.append(f"{len(waivers)} gap(s) waived at sign-off:")
            lines.append("")
            for waiver in waivers:
                lines.append(f"- **{waiver['section_key']}** — {waiver['reason']}")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"
