"""Pack → PDF (reportlab).

PDF rendering **degrades rather than blocks**. If reportlab is missing or a render fails,
`render_pdf` returns `None` and issuance proceeds with the markdown, the data snapshot and
a recorded note that the PDF was unavailable. A pack that a controller has reviewed, signed
and waived gaps on should not be un-issuable because a typesetting library is absent — the
governance record is the markdown and the hash, not the typography.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

AURORA_NAVY = "#0B1E3B"
AURORA_EMERALD = "#10B981"


def render_pdf(
    path: Path,
    pack: dict[str, Any],
    sections: list[dict[str, Any]],
    *,
    waivers: list[dict[str, Any]] | None = None,
    signoff: dict[str, Any] | None = None,
) -> Path | None:
    """Write the PDF, or return None with the reason logged by the caller."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.enums import TA_RIGHT
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import mm
        from reportlab.platypus import (
            PageBreak,
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )
    except ImportError:
        return None

    styles = getSampleStyleSheet()
    navy = colors.HexColor(AURORA_NAVY)
    emerald = colors.HexColor(AURORA_EMERALD)

    h1 = ParagraphStyle("rs-h1", parent=styles["Title"], textColor=navy, fontSize=24, spaceAfter=6)
    h2 = ParagraphStyle("rs-h2", parent=styles["Heading2"], textColor=navy, spaceBefore=14)
    body = ParagraphStyle("rs-body", parent=styles["BodyText"], fontSize=9.5, leading=14)
    meta = ParagraphStyle("rs-meta", parent=body, textColor=colors.HexColor("#64748B"), fontSize=8.5)
    gap_style = ParagraphStyle(
        "rs-gap", parent=body, textColor=colors.HexColor("#B45309"),
        backColor=colors.HexColor("#FEF3C7"), borderPadding=6, spaceBefore=4, spaceAfter=4,
    )
    right = ParagraphStyle("rs-right", parent=body, alignment=TA_RIGHT)

    cover = pack.get("cover", {})
    waiver_by_section = {w["section_key"]: w for w in (waivers or [])}
    story: list[Any] = [
        Paragraph(cover.get("title", "Report pack"), h1),
        Paragraph(f"Period {pack['period']}", meta),
        Paragraph(f"Template {pack['template_ref']} · status {pack['status']}", meta),
        Spacer(1, 6 * mm),
        Paragraph("<b>All data is synthetic.</b> Generated by ledgerfab for demonstration.", meta),
        Spacer(1, 8 * mm),
        Paragraph("Contents", h2),
    ]
    for index, section in enumerate(sections, 1):
        mark = "  —  GAP" if section.get("gaps_json") else ""
        story.append(Paragraph(f"{index}. {section['title']}{mark}", body))
    story.append(PageBreak())

    def _table(rows: list[list[str]], aligns: list[str]) -> Table:
        table = Table(rows, hAlign="LEFT", repeatRows=1)
        style = [
            ("BACKGROUND", (0, 0), (-1, 0), navy),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#E2E8F0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ]
        for index, align in enumerate(aligns):
            style.append(("ALIGN", (index, 0), (index, -1), align.upper()))
        table.setStyle(TableStyle(style))
        return table

    for section in sections:
        story.append(Paragraph(section["title"], h2))
        gaps = section.get("gaps_json") or []
        if gaps:
            for gap in gaps:
                story.append(
                    Paragraph(f"<b>Not available.</b> {gap['reason']} — {gap['detail']}", gap_style)
                )
            waiver = waiver_by_section.get(section["section_key"])
            if waiver:
                story.append(Paragraph(f"<i>Waived by {waiver['signer']}: {waiver['reason']}</i>", meta))
            continue

        content = section.get("content_json") or {}
        kind = section["type"]

        if kind == "table":
            columns = content.get("columns", [])
            header = [c["label"] or " " for c in columns]
            rows = [header] + [
                [str(row.get(c["field"], {}).get("display", "")) for c in columns]
                for row in content.get("rows", [])
            ]
            if content.get("total"):
                rows.append(
                    [str(content["total"].get(c["field"], {}).get("display", "")) for c in columns]
                )
            if len(rows) > 1:
                story.append(_table(rows, [c.get("align", "left") for c in columns]))
        elif kind == "kpi_grid":
            rows = [["Measure", "This month", "Prior month", "Change"]]
            for kpi in content.get("kpis", []):
                rows.append(
                    ["—" if kpi.get("missing") else kpi["label"],
                     kpi.get("display", ""), kpi.get("prior_display", ""), kpi.get("delta_display", "")]
                )
            story.append(_table(rows, ["left", "right", "right", "right"]))
        elif kind == "flags":
            items = content.get("items", [])
            if not items:
                story.append(Paragraph("<i>No items were flagged this period.</i>", body))
            for item in items:
                story.append(
                    Paragraph(f"<b>{item['label']}</b> ({item['severity']}) — {item['message']}", body)
                )
        elif kind == "narrative":
            text = (content.get("text") or "").strip() or "<i>Not drafted.</i>"
            story.append(Paragraph(text, body))
            if content.get("dropped_sentences"):
                story.append(
                    Paragraph(
                        f"<i>{len(content['dropped_sentences'])} sentence(s) were removed during "
                        f"drafting because a figure could not be verified.</i>",
                        meta,
                    )
                )
        story.append(Spacer(1, 4 * mm))

    if signoff:
        story += [
            PageBreak(),
            Paragraph("Sign-off", h2),
            Paragraph(f"Signed by <b>{signoff['signer']}</b> at {signoff['at']}.", body),
        ]
        for waiver in waivers or []:
            story.append(Paragraph(f"Waived — <b>{waiver['section_key']}</b>: {waiver['reason']}", body))

    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph(f"Data snapshot {pack.get('snapshot_hash', '')[:16]}", right))

    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        SimpleDocTemplate(
            str(path), pagesize=A4,
            leftMargin=18 * mm, rightMargin=18 * mm, topMargin=18 * mm, bottomMargin=18 * mm,
            title=f"{cover.get('title')} — {pack['period']}", author="ReportSmith",
        ).build(story)
    except Exception:  # noqa: BLE001 — see the module docstring: degrade, never block
        return None
    return path
