"""ledgerfab CLI.

python -m ledgerfab generate --profile realistic --seed 42 --out ../examples
python -m ledgerfab hash --profile realistic --seed 42
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

from ledgerfab import PROFILES, dataset_hash, generate
from ledgerfab.export import export_world


def _summary(world) -> dict:  # type: ignore[no-untyped-def]
    gt = world.ground_truth
    return {
        "profile": world.profile_name,
        "seed": world.seed,
        "hash": dataset_hash(world),
        "counts": {
            "counterparties": len(world.counterparties),
            "invoices": len(world.invoices),
            "transactions": len(world.transactions),
            "notes": len(world.notes),
            "gl_entries": len(world.gl_entries),
            "accruals": len(world.accruals),
            "matched": len(gt.matches),
            "exceptions": len(gt.exceptions),
        },
        "root_causes": dict(
            sorted(Counter(e.root_cause_type.value for e in gt.exceptions).items())
        ),
        "difficulty_tiers": dict(sorted(Counter(e.difficulty_tier for e in gt.exceptions).items())),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="ledgerfab", description="Synthetic finance data engine")
    sub = parser.add_subparsers(dest="command", required=True)

    for name in ("generate", "hash"):
        p = sub.add_parser(name)
        p.add_argument("--profile", default="realistic", choices=sorted(PROFILES))
        p.add_argument("--seed", type=int, default=42)
        if name == "generate":
            p.add_argument("--out", required=True, help="directory for the exported CSVs")

    args = parser.parse_args(argv)
    world = generate(args.profile, args.seed)
    summary = _summary(world)

    if args.command == "hash":
        print(summary["hash"])
        return 0

    written = export_world(world, args.out)
    summary["files"] = written
    print(json.dumps(summary, indent=2))

    # A dataset card next to the data, so the shipped CSVs are reproducible by
    # anyone who clones the repo rather than being unexplained artefacts.
    card = Path(args.out) / "DATASET.md"
    card.write_text(_dataset_card(summary), encoding="utf-8")
    return 0


def _dataset_card(s: dict) -> str:
    counts = "\n".join(f"| {k} | {v} |" for k, v in s["counts"].items())
    causes = "\n".join(f"| {k} | {v} |" for k, v in s["root_causes"].items())
    tiers = "\n".join(f"| tier {k} | {v} |" for k, v in s["difficulty_tiers"].items())
    files = "\n".join(f"| `{k}` | {v} rows |" for k, v in s["files"].items())
    return f"""# Sample dataset

> ⚠️ **All data is synthetic.** Generated by `ledgerfab`; no real company, counterparty
> or transaction appears here.

Regenerate byte-identically with:

```bash
cd backend && uv run python -m ledgerfab generate \\
    --profile {s["profile"]} --seed {s["seed"]} --out ../examples
```

| field | value |
|---|---|
| profile | `{s["profile"]}` |
| seed | `{s["seed"]}` |
| dataset hash | `{s["hash"]}` |

## Files
| file | rows |
|---|---|
{files}

`transactions.csv` contains only the **exceptions** — the residue an upstream
matcher could not clear. `prior_transactions.csv` holds the already-settled
payments, which is what makes a duplicate provable.

## Counts
| entity | n |
|---|---|
{counts}

## Ground-truth root causes
| root cause | n |
|---|---|
{causes}

## Difficulty tiers
| tier | n |
|---|---|
{tiers}
"""


if __name__ == "__main__":
    sys.exit(main())
